name: Test

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        include:
          - test: pytest
          - test: github-tag-release
          - test: github-tag-teams
          - test: github-get-ratelimit
          - test: github-list-repos
          - test: github-auth-debug
            env:
              DM_SQUARE_DEBUG: 'bogus_non_int_able_value'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install deps
        run: |
         pip install --upgrade pip build
         #if [ "${{ matrix.test }}" == "github-tag-release" ]; then
         pip install '.[test]'
            #fi
      - name: Run Tests
        env:
          SQREADMIN_TOKEN: ${{ secrets.RUBINORG_MEMBER_READONLY }}
          DM_SQUARE_DEBUG: ${{ matrix.env.DM_SQUARE_DEBUG || '' }}
        run: |
          set -e
          TEST=${{ matrix.test }}
          case "$TEST" in
            pytest)
              pytest
              ;;

            github-tag-release)
              set -e
              # check argparse help formatting for errors
              "$TEST" -h

              if [ -n "$SQREADMIN_TOKEN" ]; then
                # verify a past weekly tag -- the eups tag name and git tag names are
                # in sync except for s/_/-/
                "$TEST" \
                  --dry-run \
                  --debug \
                  --user sqreadmin \
                  --token "$SQREADMIN_TOKEN" \
                  --email sqre-admin@lists.lsst.org \
                  --versiondb-base-url https://raw.githubusercontent.com/lsst/versiondb/main/manifests \
                  --eupstag-base-url https://eups.lsst.codes/stack/src/tags \
                  --allow-team 'Data Management' \
                  --allow-team 'DM Externals' \
                  --external-team 'DM Externals' \
                  --deny-team 'DM Auxilliaries' \
                  --org lsst --manifest b7837 --eups-tag w_2025_33 w.2025.33

                # verify a past official release where the git tag was generated from
                # an rcX eups tag.  This validates the location of the git tags but
                # does not inspect the official eups release tag at all.
                "$TEST" \
                  --verify \
                  --debug \
                  --limit 10 \
                  --org 'lsst' \
                  --allow-team 'Data Management' \
                  --allow-team 'DM Externals' \
                  --external-team 'DM Externals' \
                  --deny-team 'DM Auxilliaries' \
                  --email 'sqre-admin@lists.lsst.org' \
                  --user 'sqreadmin' \
                  --token "$SQREADMIN_TOKEN" \
                  --ignore-git-tagger \
                  --ignore-git-message \
                  --eups-tag 'v28_0_2_rc1' \
                  --manifest 'b7593' \
                  '28.0.2'

                # verify a past official release using the eups tag. As the eups
                # product version strings will be out of sync between the versiondb
                # manifest it was based on and the eups tag, the eups product version
                # strings have to be ignored.
                "$TEST" \
                  --verify \
                  --debug \
                  --limit 10 \
                  --org 'lsst' \
                  --allow-team 'Data Management' \
                  --allow-team 'DM Externals' \
                  --external-team 'DM Externals' \
                  --deny-team 'DM Auxilliaries' \
                  --email 'sqre-admin@lists.lsst.org' \
                  --user 'sqreadmin' \
                  --token "$SQREADMIN_TOKEN" \
                  --ignore-manifest-versions \
                  --ignore-git-tagger \
                  --ignore-git-message \
                  --manifest 'b7593' \
                  '28.0.2'

                "$TEST" \
                  --dry-run \
                  --debug \
                  --limit 10 \
                  --org 'lsst' \
                  --allow-team 'Data Management' \
                  --allow-team 'DM Externals' \
                  --external-team 'DM Externals' \
                  --deny-team 'DM Auxilliaries' \
                  --email 'sqre-admin@lists.lsst.org' \
                  --user 'sqreadmin' \
                  --token "$SQREADMIN_TOKEN" \
                  --ignore-manifest-versions \
                  --ignore-git-tagger \
                  --ignore-git-message \
                  --manifest 'b7624' \
                  --manifest-only \
                  'w.2025.15'
              else
                echo "Unable to test without secure env vars."
              fi
              ;;

            github-tag-teams)
             "$TEST" -h
              if [ -n "$SQREADMIN_TOKEN" ]; then
              # check argparse help formatting for errors
               # create tag for release
               "$TEST" \
                 --debug \
                 --dry-run \
                 --ignore-existing-tag \
                 --org 'lsst' \
                 --allow-team 'DM Auxilliaries' \
                 --deny-team 'DM Externals' \
                 --token "$SQREADMIN_TOKEN" \
                 --user 'sqreadmin' \
                 --email 'sqre-admin@lists.lsst.org' \
                 --tag 'v29.2.0.rc1' \
                 -r 'v29.2.x' -r 'v29.1.1' -r '29.1.1' # refs may not all exist

               # create tag for weekly
               "$TEST" \
                 --debug \
                 --ignore-existing-tag \
                 --dry-run \
                 --org 'lsst' \
                 --allow-team 'DM Auxilliaries' \
                 --deny-team 'DM Externals' \
                 --token "$SQREADMIN_TOKEN" \
                 --user 'sqreadmin' \
                 --email 'sqre-admin@lists.lsst.org' \
                 --tag 'w.2025.32'

               # --delete
               "$TEST" \
                 --debug \
                 --dry-run \
                 --delete \
                 --org 'lsst' \
                 --allow-team 'DM Auxilliaries' \
                 --deny-team 'DM Externals' \
                 --token "$SQREADMIN_TOKEN" \
                 --user 'sqreadmin' \
                 --email 'sqre-admin@lists.lsst.org' \
                 --tag 'foo' \
                 --tag 'bar'
             else
               echo "Unable to test without travis secure env vars."
             fi
              ;;

            github-list-repos)
              "$TEST" -h
              if [ -n "$SQREADMIN_TOKEN" ]; then
                "$TEST" \
                  --debug \
                  --org 'lsst' \
                  --token "$SQREADMIN_TOKEN"
              else
                echo "Unable to test without travis secure env vars."
              fi
              ;;

            github-get-ratelimit)
            # check argparse help formatting for errors
             "$TEST" -h

              if [ -n "$SQREADMIN_TOKEN" ]; then
               "$TEST" \
                 --debug \
                 --token "$SQREADMIN_TOKEN"
              else
                 echo "le to test without travis secure env vars."
              fi
              ;;

            github-auth-debug)
              TEST=github-auth
              # should fail
              "$TEST" -u foo || true
              #[[ $? == 1 ]]
              ;;
            *)
              "$TEST" -h
              ;;

          esac
